### ISSUE TITLE
npm test results in "ReferenceError: WebSocket is not defined"

### ISSUE THREAD

**Issue by scottjbarr** [mehmetkose/react-websocket#10]
I'm using react-websocket 1.1.6

This is working in development, but when running `npm test` on my project I see...

``` .
    ReferenceError: WebSocket is not defined

      at new Websocket (node_modules/react-websocket/build/index.js:89:16)
      at node_modules/react/lib/ReactCompositeComponent.js:294:18
      ...
```

The line in question is...

```
ws: new WebSocket(this.props.url),
```

Should `ws` be a dev dependency?

**Comment by stevenpetryk** [comment]
In your test environment, are you sure WebSocket is an available API? WebSocket doesn't seem to be available in Node. Perhaps you could mock a `globals.WebSocket` object just for your tests. If you need complex mocking, [I found this](https://github.com/thoov/mock-socket)!

**Comment by damiangreen** [comment]
I also get this error when using Server Side Rendering

**Comment by stevenpetryk** [comment]
@damiangreen you cannot use WebSocket when doing Server Side Rendering, since WebSocket is not available in NodeJS. To get around this, you could do something like:

```js
if (typeof window !== 'undefined') {
  // use WebSocket safely, only in here
}
```

or, if you're using React, you can place all non-SSR code inside of `componentDidMount`.

**Comment by stevenpetryk** [comment]
@mehmetkose this issue can probs be closed btw—just people misusing the library.
